Adding hint/warning log for use under a MultiChildrenderObjectElement
letsar/nil pull request #1
Opened 2021-03-14 21:39 UTC by pstromberg98

2021-03-14 21:58 UTC, pstromberg98 commented
@letsar One thing I do worry about using an assert is that it throws. I think it would be safer if we just made it warn instead. Because the code is essentially assuming that the all `MultiChildRenderObjectElement` corresponding widgets take lists as arguments (which they might, I don't know), and thus can use inline conditionals or list modifications. Is that assumption safe to make?

2021-03-15 20:20 UTC, letsar commented
Thank you a lot for this!

You can make an assert than does not throw like this:
```
assert(() {
  // You can log here what you want.
  return true;
}());
```

I'm not sure a warn is safer, because the developer will maybe not read it. For the moment , until https://github.com/flutter/flutter/issues/78159 is fixed, I think we should prevent the developer to use it in this context.

What do you think?

2021-03-15 20:25 UTC, letsar commented
LGTM by the way :-)

2021-03-15 20:26 UTC, letsar reviewed
Great! Can you also increment the version to 1.1.0 and add an entry in the changelog?

2021-03-16 00:49 UTC, pstromberg98 commented
Yeah my only worry is if there is a situation in which a MultiChildRenderObjectElement is created from a widget that doesn't take in a list. But I don't think that there are any widget-element pairs are like that so I am fine having it throw if you are.

2021-03-16 18:25 UTC, letsar commented
In fact it would be even more important in that context, don't you think?

2021-03-16 18:54 UTC, pstromberg98 commented
@letsar Yes I suppose so. Because they could just use Nil instead of the hypothetical widget with a Nil child?

Regardless, looking at the documentation the `MultiChildRenderObjectElement` requires a `MultiChildRenderObjectWidget` (which takes a list) so I don't think my hypothetical example would ever actually happen.

2021-03-18 07:26 UTC, letsar requested changes
Great, thanks again :-). Just a minor change in the changelog, and I will accept this PR :-)

2021-03-18 07:26 UTC, letsar commented on CHANGELOG.md
> +## [1.1.1]
Can you also add this link below [Unreleased]?

`[1.1.1]: https://github.com/letsar/binder/compare/releases/tag/v1.1.1`

2021-03-23 14:52 UTC, pstromberg98 commented
@letsar Is this going to be merged still?

2021-03-24 07:07 UTC, letsar approved these changes
LGTM

2021-03-24 07:07 UTC, merged

2021-03-24 07:15 UTC, letsar commented
Merged and published. Thank you again Parker :-)